// This file is @generated by prost-build.
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CsRpcMsg {
    #[prost(enumeration = "CsRpcCmd", tag = "1")]
    pub cmd: i32,
    #[prost(uint32, tag = "2")]
    pub seq: u32,
    #[prost(uint32, tag = "3")]
    pub session_id: u32,
    #[prost(oneof = "cs_rpc_msg::Payload", tags = "10, 11, 12, 13")]
    pub payload: ::core::option::Option<cs_rpc_msg::Payload>,
}
/// Nested message and enum types in `CSRpcMsg`.
pub mod cs_rpc_msg {
    #[allow(non_camel_case_types)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "10")]
        PlaceholderReq(super::PlaceholderReq),
        #[prost(message, tag = "11")]
        PlaceholderResp(super::PlaceholderResp),
        #[prost(message, tag = "12")]
        HeartbeatReq(super::HeartbeatReq),
        #[prost(message, tag = "13")]
        HeartbeatResp(super::HeartbeatResp),
    }
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceholderReq {
    #[prost(string, tag = "1")]
    pub msg: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceholderResp {
    #[prost(string, tag = "1")]
    pub msg: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatReq {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatResp {
    #[prost(uint64, tag = "1")]
    pub timestamp: u64,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CsRpcCmd {
    Unspecified = 0,
    Placeholder = 1,
    Heartbeat = 2,
}
impl CsRpcCmd {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CS_RPC_CMD_UNSPECIFIED",
            Self::Placeholder => "CS_RPC_CMD_PLACEHOLDER",
            Self::Heartbeat => "CS_RPC_CMD_HEARTBEAT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CS_RPC_CMD_UNSPECIFIED" => Some(Self::Unspecified),
            "CS_RPC_CMD_PLACEHOLDER" => Some(Self::Placeholder),
            "CS_RPC_CMD_HEARTBEAT" => Some(Self::Heartbeat),
            _ => None,
        }
    }
}
