// This file is @generated by prost-build.
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CsRpcMsg {
    #[prost(enumeration = "CsRpcCmd", tag = "1")]
    pub cmd: i32,
    #[prost(uint32, tag = "2")]
    pub seq: u32,
    #[prost(uint32, tag = "3")]
    pub session_id: u32,
    #[prost(oneof = "cs_rpc_msg::Payload", tags = "14, 15")]
    pub payload: ::core::option::Option<cs_rpc_msg::Payload>,
}
/// Nested message and enum types in `CSRpcMsg`.
pub mod cs_rpc_msg {
    #[allow(non_camel_case_types)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "14")]
        LoginReq(super::LoginReq),
        #[prost(message, tag = "15")]
        LoginResp(super::LoginResp),
    }
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LoginReq {
    #[prost(uint32, tag = "1")]
    pub player_id: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResp {
    #[prost(message, optional, tag = "1")]
    pub player_data: ::core::option::Option<super::model::PlayerData>,
    #[prost(string, tag = "2")]
    pub error_msg: ::prost::alloc::string::String,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CsRpcCmd {
    Unspecified = 0,
    LoginReq = 3,
    LoginResp = 4,
}
impl CsRpcCmd {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CS_RPC_CMD_UNSPECIFIED",
            Self::LoginReq => "CS_RPC_CMD_LOGIN_REQ",
            Self::LoginResp => "CS_RPC_CMD_LOGIN_RESP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CS_RPC_CMD_UNSPECIFIED" => Some(Self::Unspecified),
            "CS_RPC_CMD_LOGIN_REQ" => Some(Self::LoginReq),
            "CS_RPC_CMD_LOGIN_RESP" => Some(Self::LoginResp),
            _ => None,
        }
    }
}
