// This file is @generated by prost-build.
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerBase {
    #[prost(uint64, tag = "1")]
    pub player_id: u64,
    #[prost(string, tag = "2")]
    pub player_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub player_level: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerBagItem {
    #[prost(uint32, tag = "1")]
    pub item_id: u32,
    #[prost(uint32, tag = "2")]
    pub item_count: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerBagMoney {
    #[prost(enumeration = "PlayerBagMoneyType", tag = "1")]
    pub money_type: i32,
    #[prost(uint32, tag = "2")]
    pub money_count: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerBag {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<PlayerBagItem>,
    #[prost(message, repeated, tag = "2")]
    pub money: ::prost::alloc::vec::Vec<PlayerBagMoney>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerSkill {
    #[prost(uint32, tag = "1")]
    pub skill_id: u32,
    #[prost(uint32, tag = "2")]
    pub skill_level: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerSkillData {
    #[prost(uint32, tag = "1")]
    pub skill_points: u32,
    #[prost(message, repeated, tag = "2")]
    pub skills: ::prost::alloc::vec::Vec<PlayerSkill>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerData {
    #[prost(message, optional, tag = "1")]
    pub player_base: ::core::option::Option<PlayerBase>,
    #[prost(message, optional, tag = "2")]
    pub player_bag: ::core::option::Option<PlayerBag>,
    #[prost(message, optional, tag = "3")]
    pub player_skill: ::core::option::Option<PlayerSkillData>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerBaseDelta {
    #[prost(uint32, optional, tag = "1")]
    pub player_level: ::core::option::Option<u32>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerBagMoneyDelta {
    #[prost(enumeration = "PlayerBagMoneyType", tag = "1")]
    pub money_type: i32,
    #[prost(uint32, tag = "2")]
    pub money_count: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerBagItemDelta {
    #[prost(enumeration = "DeltaOp", tag = "1")]
    pub op: i32,
    #[prost(uint32, tag = "2")]
    pub item_id: u32,
    #[prost(uint32, tag = "3")]
    pub item_count: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerBagDelta {
    #[prost(message, repeated, tag = "1")]
    pub money_changes: ::prost::alloc::vec::Vec<PlayerBagMoneyDelta>,
    #[prost(message, repeated, tag = "2")]
    pub item_changes: ::prost::alloc::vec::Vec<PlayerBagItemDelta>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PlayerSkillDelta {
    #[prost(enumeration = "DeltaOp", tag = "1")]
    pub op: i32,
    #[prost(uint32, tag = "2")]
    pub skill_id: u32,
    #[prost(uint32, tag = "3")]
    pub skill_level: u32,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerSkillDataDelta {
    #[prost(uint32, optional, tag = "1")]
    pub skill_points: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "2")]
    pub skill_changes: ::prost::alloc::vec::Vec<PlayerSkillDelta>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerDataDelta {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<PlayerBaseDelta>,
    #[prost(message, optional, tag = "2")]
    pub bag: ::core::option::Option<PlayerBagDelta>,
    #[prost(message, optional, tag = "3")]
    pub skill: ::core::option::Option<PlayerSkillDataDelta>,
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PlayerBagMoneyType {
    Unspecified = 0,
    Gold = 1,
    Diamond = 2,
}
impl PlayerBagMoneyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PLAYER_BAG_MONEY_TYPE_UNSPECIFIED",
            Self::Gold => "PLAYER_BAG_MONEY_TYPE_GOLD",
            Self::Diamond => "PLAYER_BAG_MONEY_TYPE_DIAMOND",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PLAYER_BAG_MONEY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "PLAYER_BAG_MONEY_TYPE_GOLD" => Some(Self::Gold),
            "PLAYER_BAG_MONEY_TYPE_DIAMOND" => Some(Self::Diamond),
            _ => None,
        }
    }
}
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeltaOp {
    Unspecified = 0,
    Upsert = 1,
    Delete = 2,
}
impl DeltaOp {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DELTA_OP_UNSPECIFIED",
            Self::Upsert => "DELTA_OP_UPSERT",
            Self::Delete => "DELTA_OP_DELETE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DELTA_OP_UNSPECIFIED" => Some(Self::Unspecified),
            "DELTA_OP_UPSERT" => Some(Self::Upsert),
            "DELTA_OP_DELETE" => Some(Self::Delete),
            _ => None,
        }
    }
}
